### ISSUE TITLE
大佬请问几个问题

### ISSUE THREAD

**Issue by RenZMin** [ericet/kexuejia#1]
最近在学习大佬的文章和代码 
想问下大佬，ABI中的ifo.json是如何拿到的呢，通过分析网页源码吗？我查合约 看起来合约是闭源的
这个ifo中的合约地址，也是通过网页源码拿到吗？ 希望大佬能指教一下 谢谢

**Comment by RenZMin** [comment]
> 那个IFO从pancake的合约那里找到的 https://bscscan.com/address/0x1B2A2f6ed4A1401E8C73B4c2B6172455ce2f78E8#code

大佬 请问下0x1B2A2f6ed4A1401E8C73B4c2B6172455ce2f78E8 这个ifo pool的合约地址 是从哪里可以查的到呀，我看另外一个pancake的js里 pool的合约地址是0x63914805A0864e9557eA3A5cC86cc1BA054ec64b
谢谢大佬

**Comment by ericet** [comment]
0x1B2A2f6ed4A1401E8C73B4c2B6172455ce2f78E8 这个是那个质押CAKE获得IFO额度的合约，0x63914805A0864e9557eA3A5cC86cc1BA054ec64b 是IFO项目参与的合约，记得之前是有IFO的时候，页面有显示这个合约

**Comment by RenZMin** [comment]
> 



> 0x1B2A2f6ed4A1401E8C73B4c2B6172455ce2f78E8 这个是那个质押CAKE获得IFO额度的合约，0x63914805A0864e9557eA3A5cC86cc1BA054ec64b 是IFO项目参与的合约，记得之前是有IFO的时候，页面有显示这个合约

嗯嗯 我明白了 感谢
