### ISSUE TITLE
你好，就是关于生成消息签名的那个教程，签名的内容需要怎么来确定

### ISSUE THREAD

**Issue by izz520** [ericet/kexuejia#3]
我看您写的那个教程里面有一个签名的信息

```
//需要签名的信息
const msg = "I consent to be included in the Prime Ape Planet raffle.\n\nNo gas fee will be needed to perform this action."
```

想问一下您，这一行的内容信息该如何去确定，就是比如在一个网站需要签名，但是这个签名的信息我需要怎么来确定呢

**Comment by ericet** [comment]
信息是项目方决定的。去网站实际操作一下就可以看到他们的消息

**Comment by izz520** [comment]
![image](https://user-images.githubusercontent.com/44974907/163134606-28020bd1-9b87-444a-b34b-6407c505e0b4.png)


像这个secondlive网站的签名，在签名的时候显示的消息不是内容，而是加密过的内容，那我要如何来模拟这个签名呢

**Comment by ericet** [comment]
这个签名的逻辑需要自己琢磨

**Comment by izz520** [comment]
哈哈 好哒，谢谢啦，我也会持续关注你的教程，非常有用
